#!/bin/bash

list=( 
hipChooseDevice
hipDeviceGetAttribute
hipDeviceGetByPCIBusId
hipDeviceGetLimit
hipDeviceGetP2PAttribute
hipDeviceGetPCIBusId
hipDeviceGetSharedMemConfig
hipDeviceGetStreamPriorityRange
hipDeviceReset
hipDeviceSetLimit
hipDeviceSetSharedMemConfig
hipDeviceSynchronize
hipGetDevice
hipGetDeviceCount
hipGetDeviceFlags
hipGetDeviceProperties
hipIpcCloseMemHandle
hipIpcGetEventHandle
hipIpcGetMemHandle
hipIpcOpenEventHandle
hipIpcOpenMemHandle
hipSetDevice
hipSetDeviceFlags
hipDeviceReset
hipDeviceGetCacheConfig
hipDeviceSetCacheConfig
hipGetErrorName
hipGetErrorString
hipGetLastError
hipPeekAtLastError
hipStreamAddCallback
hipStreamAttachMemAsync
hipStreamCreate
hipStreamCreateWithFlags
hipStreamCreateWithPriority
hipStreamDestroy
hipStreamGetFlags
hipStreamGetPriority
hipStreamQuery
hipStreamSynchronize
hipStreamWaitEvent
hipEventCreate
hipEventCreateWithFlags
hipEventDestroy
hipEventElapsedTime
hipEventQuery
hipEventRecord
hipEventSynchronize
hipFuncGetAttributes
hipFuncSetAttribute
hipFuncSetCacheConfig
hipFuncSetSharedMemConfig
hipLaunchCooperativeKernel
hipLaunchCooperativeKernelMultiDevice
hipLaunchKernel
hipOccupancyMaxActiveBlocksPerMultiprocessor
hipOccupancyMaxActiveBlocksPerMultiprocessorWithFlags
hipOccupancyMaxPotentialBlockSize
hipOccupancyMaxPotentialBlockSizeWithFlags
hipFree
hipFreeArray
hipHostFree
hipFreeMipmappedArray
hipGetMipmappedArrayLevel
hipGetSymbolAddress
hipGetSymbolSize
hipHostMalloc
hipHostGetDevicePointer
hipHostGetFlags
hipHostRegister
hipHostUnregister
hipMalloc
hipMalloc3D
hipMalloc3DArray
hipMallocArray
hipMallocManaged
hipMallocMipmappedArray
hipMallocPitch
hipMemAdvise
hipMemGetInfo
hipMemPrefetchAsync
hipMemRangeGetAttribute
hipMemRangeGetAttributes
hipMemcpy
hipMemcpy2D
hipMemcpy2DAsync
hipMemcpy2DFromArray
hipMemcpy2DFromArrayAsync
hipMemcpy2DToArray
hipMemcpy3D
hipMemcpy3DAsync
hipMemcpyAsync
hipMemcpyFromSymbol
hipMemcpyFromSymbolAsync
hipMemcpyPeer
hipMemcpyPeerAsync
hipMemcpyToSymbol
hipMemcpyToSymbolAsync
hipMemset
hipMemset2D
hipMemset2DAsync
hipMemset3D
hipMemset3DAsync
hipMemsetAsync
hipExtent
hipPitchedPtr
hipPos
hipMemcpyFromArray
hipMemcpyToArray
hipMemcpyToArrayAsync
hipPointerGetAttributes
hipDeviceCanAccessPeer
hipDeviceDisablePeerAccess
hipDeviceEnablePeerAccess
hipBindTexture
hipBindTexture2D
hipBindTextureToArray
hipBindTextureToMipmappedArray
hipCreateChannelDesc
hipGetChannelDesc
hipGetTextureAlignmentOffset
hipGetTextureReference
hipUnbindTexture
hipGetTextureObjectTextureDesc
hipCreateTextureObject
hipDestroyTextureObject
hipGetTextureObjectResourceDesc
hipGetTextureObjectResourceViewDesc
hipCreateSurfaceObject
hipDestroySurfaceObject
hipDriverGetVersion
hipRuntimeGetVersion
hipProfilerStart
hipProfilerStop
hipConfigureCall
hipLaunchByPtr
hipSetupArgument )


directories=( "benchmarks/performance/BabelStream"
"benchmarks/performance/cs-roofline-toolkit"
"applications/cholla"
"proxies/KokkosDslash"
"proxies/su3_bench"
"proxies/adept-proxy"
"proxies/BerkeleyGW-Kernels-CPP"
"HIP-Examples/add4"
"HIP-Examples/cuda-stream"
"HIP-Examples/gpu-burn"
"HIP-Examples/mini-nbody"
"HIP-Examples/reduction"
"HIP-Examples/rodinia_3.0"
"HIP-Examples/rtm8"
"HIP-Examples/strided-access"
"HIP-Examples/vectorAdd"
"HIP-Examples/GPU-STREAM"
"HIP-Examples/mixbench"
"HIP-Examples/HIP-Examples-Applications/BinomialOption"
"HIP-Examples/HIP-Examples-Applications/BitonicSort"
"HIP-Examples/HIP-Examples-Applications/FastWalshTransform"
"HIP-Examples/HIP-Examples-Applications/FloydWarshall"
"HIP-Examples/HIP-Examples-Applications/HelloWorld"
"HIP-Examples/HIP-Examples-Applications/Histogram"
"HIP-Examples/HIP-Examples-Applications/MatrixMultiplication"
"HIP-Examples/HIP-Examples-Applications/PrefixSum"
"HIP-Examples/HIP-Examples-Applications/RecursiveGaussian"
"HIP-Examples/HIP-Examples-Applications/SimpleConvolution"
"HIP-Examples/HIP-Examples-Applications/dct"
"HIP-Examples/HIP-Examples-Applications/dwtHaar1D"
"frameworks/kokkos"
"frameworks/RAJA"
"frameworks/occa"
	    )

for d in ${directories[@]} 
do
    e=$(basename $d )
    rm -f output_$e
    for i in ${list[@]} 
    do
	grep -r "$i" $d |& tee -a output_${e}
    done
done

for d in "${directories[@]}"
do
    e=$(basename $d)
    echo \"$d\" : \"output_$e\",
done
